jbosstools/jbosstools-download.jboss.org

- jbosstools/updates/requirements/bpmn2-modeler/build.xml
Update both bpmn2 feature and modeler/editor - used in JBTIS TP 4.2.0.Final.
> JBTIS-378 - bpmn2 modeler 1.1.1 - Luna update

- jbosstools/targetplatforms/jbtistarget/mars/compositeArtifacts.xml
- jbosstools/targetplatforms/jbtistarget/mars/compositeContent.xml
Latest Mars JBTIS TP - locus update + Alpha2 core TP.
> JBTIS TP 4.3.0.Alpha1b

- jbosstools/updates/requirements/bpel/build.xml
> JBTIS-461 - bpel 1.0.5

- jbosstools/mars/stable/updates/compositeArtifacts.xml
- jbosstools/mars/stable/updates/compositeContent.xml
switch staging site to include 4.3.0.Final + egit 4.1.1
JBIDE-21821 add egit 4.1.1 to stable JBT 4.3.0.Final composite site
> JBIDE-21821 include 4.3.0.Final + egit 4.1.1 in composite

- jbosstools/updates/requirements/bpmn2-modeler/neon/build.xml
Update BPMN2 Modeler to 1.3.0.Final (Neon)
> JBTIS-730 - BPMN2 1.3.0.Final - neon

- jbosstools/osio/index.html
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> Add OSIO landing page

- jbosstools/osio/index.html
- adds copy to clipboard option for OSIO landing screen
Signed-off-by: Jaivardhan Kumar <jakumar@redhat.com>
> adds copy to clipboard option

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.current-snapshots-fragment.properties
Update ide-config.properties for Devstudio 11.2.0.GA/JBT 4.5.2.Final
Signed-off-by: Lukáš Valach <lvalach@redhat.com>
> Update ide-config.properties for Devstudio 11.2.0.GA/JBT 4.5.2.Final

- jbosstools/oxygen/development/updates/integration-stack/compositeArtifacts.xml
- jbosstools/oxygen/development/updates/integration-stack/compositeContent.xml
- jbosstools/oxygen/development/updates/integration-stack/discovery/compositeArtifacts.xml
- jbosstools/oxygen/development/updates/integration-stack/discovery/compositeContent.xml
- jbosstools/oxygen/development/updates/integration-stack/discovery/earlyaccess/compositeArtifacts.xml
- jbosstools/oxygen/development/updates/integration-stack/discovery/earlyaccess/compositeContent.xml
- jbosstools/oxygen/stable/updates/compositeArtifacts.xml
- jbosstools/oxygen/stable/updates/compositeContent.xml
- jbosstools/oxygen/stable/updates/discovery.earlyaccess/4.5.2.Final/jbosstools-directory.xml
- jbosstools/oxygen/stable/updates/integration-stack/compositeArtifacts.xml
- jbosstools/oxygen/stable/updates/integration-stack/compositeContent.xml
- jbosstools/oxygen/stable/updates/integration-stack/discovery/compositeArtifacts.xml
- jbosstools/oxygen/stable/updates/integration-stack/discovery/compositeContent.xml
- jbosstools/oxygen/staging/updates/integration-stack/compositeArtifacts.xml
- jbosstools/oxygen/staging/updates/integration-stack/compositeContent.xml
- jbosstools/oxygen/staging/updates/integration-stack/discovery/compositeArtifacts.xml
- jbosstools/oxygen/staging/updates/integration-stack/discovery/compositeContent.xml
- jbosstools/oxygen/staging/updates/integration-stack/discovery/earlyaccess/compositeArtifacts.xml
- jbosstools/oxygen/staging/updates/integration-stack/discovery/earlyaccess/compositeContent.xml
- jbosstools/targetplatforms/jbtistarget/oxygen/compositeArtifacts.xml
- jbosstools/targetplatforms/jbtistarget/oxygen/compositeContent.xml
Signed-off-by: Paul Leacu <pleacu@redhat.com>
> JBTIS-1194 - update to JBTIS 4.5.2.Final

- jbosstools/configuration/src/main/ide-config.other-fragment.properties
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> Add missing examples URLs for 4.9

- jbosstools/configuration/src/main/ide-config.current-snapshots-fragment.properties
- jbosstools/configuration/src/main/ide-config.current-staging-fragment.properties
- jbosstools/static/redhat-central/README.html
> Tentative fix central webpage URL for staging process.

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.other-fragment.properties
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> JBIDE-26948: update ide-config.properties to include examples for 4.14

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.current-stable-fragment.properties
- jbosstools/configuration/src/main/ide-config.current-staging-fragment.properties
> JBIDE-26956: fix JBossTools central config

- README.md
- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.other-fragment.properties
- jbosstools/examples/README.html
- jbosstools/static/redhat-central/README.html
> Migrating issues.jboss.org --> issues.redhat.com

- jbosstools/updates/requirements/wildwebdeveloper/build.xml
> added wildwebdeveloper

- jbosstools/configuration/ide-config.properties
> fix config.properties after 4.14.0.Final release

- jbosstools/configuration/ide-config.properties
> fix central build for missing examples url

- jbosstools/updates/requirements/cdt/build.xml
> added CDT 9.11

- jbosstools/configuration/ide-config.properties
> fix config.properties for 4.15.0.Final

- jbosstools/updates/requirements/springide/build.xml
> JBIDE-27151: update SpringIDE IUs to mirror

- jbosstools/configuration/ide-config.properties
> fix config.properties for 4.16.0.AM1

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.current-development-fragment.properties
- jbosstools/configuration/src/main/ide-config.current-staging-fragment.properties
> JBIDE-27181: fixed ide-config.properties for 4.16.0.AM1 release

- jbosstools/updates/requirements/springide/build.xml
> JBIDE-27327 : fix springide mirror

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.current-stable-fragment.properties
- jbosstools/configuration/src/main/ide-config.other-fragment.properties
> update ide-config*.properties for JBT 4.16.0.Final / devstudio 12.16.0.GA

- jbosstools/configuration/src/main/ide-config.current-snapshots-fragment.properties
- jbosstools/configuration/src/main/ide-config.current-staging-fragment.properties
> JBDS-4876: remove integration stack urls from central

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/pom.xml
- jbosstools/configuration/src/main/ide-config.current-development-fragment.properties
- jbosstools/configuration/src/main/ide-config.current-stable-fragment.properties
- jbosstools/configuration/src/main/ide-config.current-staging-fragment.properties
- jbosstools/configuration/src/main/ide-config.other-fragment.properties
> update ide-config*.properties for stable release of jbosstools 4.18.0.Final / devstudio 12.18.0.GA

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.current-development-fragment.properties
jbosstools 4.19.0.AM1 / devstudio 12.19.0.AM1
> fixed update ide-config*.properties for development release of

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.current-snapshots-fragment.properties
- jbosstools/configuration/src/main/ide-config.current-stable-fragment.properties
- jbosstools/configuration/src/main/ide-config.other-fragment.properties
> prepare 4.19.1.AM1

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.other-fragment.properties
> Add examples for 4.21

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.current-development-fragment.properties
- jbosstools/configuration/src/main/ide-config.current-snapshots-fragment.properties
- jbosstools/configuration/src/main/ide-config.current-staging-fragment.properties
> prepare 4.23.0.Final

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.current-snapshots-fragment.properties
- jbosstools/configuration/src/main/ide-config.current-stable-fragment.properties
- jbosstools/configuration/src/main/ide-config.other-fragment.properties
> fix ide-config*.properties for stable release of jbosstools 4.23.0.Final

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.current-stable-fragment.properties
- jbosstools/configuration/src/main/ide-config.other-fragment.properties
> fix after 4.25.0.AM1 parent update

- jbosstools/photon/development/updates/README.html
- jbosstools/photon/development/updates/compositeArtifacts.xml
- jbosstools/photon/development/updates/compositeContent.xml
- jbosstools/photon/development/updates/discovery.central/compositeArtifacts.xml
- jbosstools/photon/development/updates/discovery.central/compositeContent.xml
- jbosstools/photon/development/updates/discovery.earlyaccess/compositeArtifacts.xml
- jbosstools/photon/development/updates/discovery.earlyaccess/compositeContent.xml
- jbosstools/photon/development/updates/integration-stack/README.html
- jbosstools/photon/snapshots/builds/_composite_/core/master/compositeArtifacts.xml
- jbosstools/photon/snapshots/builds/_composite_/core/master/compositeContent.xml
- jbosstools/photon/stable/updates/README.html
- jbosstools/photon/stable/updates/compositeArtifacts.xml
- jbosstools/photon/stable/updates/compositeContent.xml
- jbosstools/photon/stable/updates/discovery.central/compositeArtifacts.xml
- jbosstools/photon/stable/updates/discovery.central/compositeContent.xml
- jbosstools/photon/stable/updates/discovery.earlyaccess/compositeArtifacts.xml
- jbosstools/photon/stable/updates/discovery.earlyaccess/compositeContent.xml
- jbosstools/photon/stable/updates/integration-stack/README.html
- jbosstools/photon/staging/updates/README.html
- jbosstools/photon/staging/updates/compositeArtifacts.xml
- jbosstools/photon/staging/updates/compositeContent.xml
- jbosstools/photon/staging/updates/integration-stack/README.html
- jbosstools/static/mars/stable/updates/integration-stack/earlyaccess/compositeArtifacts.xml
- jbosstools/static/mars/stable/updates/integration-stack/earlyaccess/compositeContent.xml
> JBIDE-26888: use https everywhere

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.other-fragment.properties
> JBIDE-27777: remove example

- jbosstools/configuration/ide-config.properties
- jbosstools/configuration/src/main/ide-config.current-snapshots-fragment.properties
> JBIDE-28677: Use new central webpage
